version: "3"
services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN=your-bot-token
      - DISCORD_CLIENT_ID=your-client-id
      - MONGO_URI=mongodb://mongodb:27017/discord-bot
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
