version: "3"
services:
  bot:
    build: 
      context: .
    container_name: shounengaming-bot-ts
    environment:
      - DISCORD_TOKEN=your-bot-token
      - DISCORD_CLIENT_ID=your-client-id
      - SOFI_MIN_EVENT_DROPS=20
      - SOFI_MAX_EVENT_DROPS=70 
      - SOFI_CATEGORY_ID=your-bot-id
      - SOFI_EVENT_DROPS_LOGS_CHANNEL_ID=channel-id
      - MONGO_URI=mongodb://mongodb:27017/shounengaming-bot-db
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: shounengaming-bot-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
